### ISSUE TITLE
Processing entire abf file as well as multiple files

### ISSUE THREAD

**Issue by najohink** [bellstwohearted/AutoNanopore#1]
Hi,

I was giving AutoNanopore a test run with a single file and noticed it said:

```
Processing started
sampling rate is 500000
total number of data point is 5000000
total length of the file is 10.0s
333 slices generated
334 valid slices selected
Optimizing ...
Processing finished within 1.99s, 6 events detected.
```

The total length of the file I input is 200 seconds (20 sweeps for 10 seconds each), how do I get AutoNanopore to go through the entire file and not just the first sweep? 

Also was wondering if its possible to input many files, or if I have to do them one by one and concatenate the csv's afterwards? I tried to use path/to/folder/*.abf for the file input but got an error.

Thanks!

best,
S

**Comment by bellstwohearted** [comment]
Hi, thanks for reaching us.

_For your 2nd question:_  bash does not support to run multiple python functions in such a way, please try the following command:

`for i in path/to/folder/*.abf; do echo $i; python AutoNanopore.py --file_path $i --output_path output/path/; done
`

 _For your 1st question:_  we are testing the usage of AutoNanopore on multiple-sweep abf files, and will reply to you later.  It would be perfect if you could provide your raw file. Since the length of each sweep is small, we suggest to reduce the ` window_size` to `10` or even smaller, so that sufficient slices are generated which favor the statistical analysis.

**Comment by bellstwohearted** [comment]
I am closing this issue, you can create a new one if you have further questions.
